### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by idriss3399** [Zarhouny/Reddit-Tiktok-video-maker#1]
New folder\Reddit-Tiktok-video-maker-main\main.py", line 24, in <module>
    py_obj.setProperty('voice', py_obj.getProperty('voices')[1].id)
IndexError: list index out of range

**Comment by Zarhouny** [comment]
> 

You only have one voice installed on your machine, install other voices. OR you can change the index to 0 to have a female voice only!
